# Generated by Django 5.0.7 on 2024-08-03 09:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("-transaction_date",)},
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="email",
            field=models.EmailField(default="admin@admin.com", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="name",
            field=models.CharField(default="biplav", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="phone",
            field=models.CharField(default="9090909090", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(default="asdf", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["transaction_id"], name="transaction_transac_10896e_idx"),
        ),
    ]
