# Generated by Django 5.0.7 on 2024-08-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_alter_transaction_options_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="phone",
            field=models.CharField(max_length=100),
        ),
    ]
