# Generated by Django 5.0.7 on 2024-08-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_alter_transaction_email_alter_transaction_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="updated_by",
        ),
    ]
