# Generated by Django 5.0.7 on 2024-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_title",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("Manager", "Manager")], default="Staff", max_length=100
            ),
        ),
    ]
